language: cpp
compiler: gcc
sudo: required

compiler:
  - clang
  - gcc

packages:
  - cmake-data
  - cmake
  
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libwxgtk3.0-dev
  
before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - pwd
  - make

