version: 1.0.{build}
image: Visual Studio 2017
clone_folder: C:\projects\wxminvscmake
install:
- cmd: >-
    REM SET WX_VS_VER=2019

    call initwx.bat
build_script:
- cmd: >-
    REM call buildwx.bat Win64 Debug static

    REM call build-wxhello.bat Win64 Debug static

    REM call buildwx.bat Win64 Debug dynamic

    REM call build-wxhello.bat Win64 Debug dynamic


    REM call buildwx.bat Win64 Release static

    REM call build-wxhello.bat Win64 Release static

    REM call buildwx.bat Win64 Release dynamic

    REM call build-wxhello.bat Win64 Release dynamic


    REM call buildwx.bat Win32 Debug static

    REM call build-wxhello.bat Win32 Debug static

    REM call buildwx.bat Win32 Debug dynamic

    REM call build-wxhello.bat Win32 Debug dynamic


    call buildwx.bat Win32 Release static

    call build-wxhello.bat Win32 Release static

    call buildwx.bat Win32 Release dynamic

    call build-wxhello.bat Win32 Release dynamic