version: 1.0.{build}
image: Visual Studio 2017

init:
- cmd: cmake --version

install:
- cmd: "cd C:\\tools\\vcpkg"
- cmd: "git pull"
- cmd: ".\\bootstrap-vcpkg.bat"

- cmd: "set VCPKG_ARCH=x64-windows"
- cmd: "echo VCPKG_ARCH:%VCPKG_ARCH%"
- cmd: "vcpkg install --recurse --triplet %VCPKG_ARCH% wxwidgets"
- cmd: "vcpkg install --recurse --triplet %VCPKG_ARCH%-static wxwidgets"

- cmd: "vcpkg integrate install"
- cmd: "cd \"%APPVEYOR_BUILD_FOLDER%\""

platform:
  - x64

cache: c:\tools\vcpkg\installed\
  
configuration:
  - Debug
  - Release
build_script:
- cmd: if "%platform%"=="x64" ( set TARGET_PLATFORM=Win64 ) else ( set TARGET_PLATFORM=Win32 )
- cmd: "SET VCPKG=C:\\tools\\vcpkg"
- cmd: "CALL buildmsvc.bat %TARGET_PLATFORM% %configuration% dynamic"
- cmd: "CALL buildmsvc.bat %TARGET_PLATFORM% %configuration% static"