version: 1.0.{build}
image: Visual Studio 2017
init:
- cmd: cmake --version
environment:
  platform: x64
install:
- cmd: "cd C:\\tools\\vcpkg\ngit pull\n.\\bootstrap-vcpkg.bat\n  \nif \"%platform%\"==\"Win32\" set VCPKG_ARCH=x86-windows\nif \"%platform%\"==\"x64\"   set VCPKG_ARCH=x64-windows\necho VCPKG_ARCH:%VCPKG_ARCH%\nvcpkg remove --outdated --recurse\nvcpkg install --recurse --triplet %VCPKG_ARCH% wxwidgets\nvcpkg integrate install\ncd \"%APPVEYOR_BUILD_FOLDER%\""
build_script:
- cmd: "SET VCPKG=C:\\tools\\vcpkg\n\nSET \"arch=Win64\"\nSET \"generator=Visual Studio 15 2017 Win64\"\nSET \"build=Release\" \n\nSET \"linking=dynamic\"\n\nset \"builddir=%build%%arch%%linking%\" \necho Building %build% %arch% using %linking% libraries..\ncmake -G \"%generator%\" -DCMAKE_BUILD_TYPE=%build% -H. -B%builddir% -DCMAKE_TOOLCHAIN_FILE=%VCPKG%\\scripts\\buildsystems\\vcpkg.cmake -DLINKING_TYPE=%linking%\ncmake --build .\\%builddir% --config %build%"